### ISSUE TITLE
Docker-compose.yml containers username

### ISSUE THREAD

**Issue by luebken** [giantswarm/giantswarm-firstapp-java#6]
https://github.com/giantswarm/giantswarm-firstapp-java/blob/master/docker-compose.yml#L2 contains @puja108 username.

**Comment by puja108** [comment]
oh, you're right, I'll have to add docker-compose to the make file and remove my username, thanks for pointing this out!

**Comment by puja108** [comment]
looked into it, and it looks like this is an open issue since fig times, which is also not looking to be fixed in docker compose:
https://github.com/docker/compose/issues/495
Only option will be have it in the readme and guide that if you want to try out stuff with docker compose you will have to change the docker-compose.yml manually.
